# Generated by Django 4.2.20 on 2025-03-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
