# Generated by Django 4.2.20 on 2025-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(default=654158175, unique=True),
            preserve_default=False,
        ),
    ]
